version: '3.8'

services:
  mysql-db:
    image: mysql:latest
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: techchallenge
      MYSQL_DATABASE: goodburguer
      MYSQL_USER: admin
      MYSQL_PASSWORD: techchallenge
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - techchallenge-network
      
  sonarqube:
    image: sonarqube
    ports:
      - "9000:9000"
      - "9092:9092"
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://sonarqube-db:5432/sonar
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
    volumes:
      - ./sonarqube/conf:/opt/sonarqube/conf
      - ./sonarqube/sonarqube_data:/opt/sonarqube/data
      
  goodburguer:
    image: felipecarvalhodesouza/goodburguer:1.0
    ports:
      - "8080:8080"
    networks:
      - techchallenge-network
    depends_on:
      - mysql-db
  
networks:
  techchallenge-network:

volumes:
  mysql-data:
  sonarqube_data: