version: '3.8'

services:
  mysql-db:
    image: mysql:latest
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: techchallenge
      MYSQL_DATABASE: goodburguer
      MYSQL_USER: admin
      MYSQL_PASSWORD: techchallenge
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - techchallenge-network

  
networks:
  techchallenge-network:

volumes:
  mysql-data:
  sonarqube_data: