version: '3.8'

services:
  mysql-db:
    image: mysql:latest
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: techchallenge
      MYSQL_DATABASE: goodburguer
      MYSQL_USER: admin
      MYSQL_PASSWORD: techchallenge
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      
  sonarqube:
    image: sonarqube
    ports:
      - "9000:9000"
      - "9092:9092"
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://sonarqube-db:5432/sonar
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
    networks:
      - sonarqube-network
    depends_on:
      - sonarqube-db

  sonarqube-db:
    image: postgres
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonar
    networks:
      - sonarqube-network
    volumes:
      - sonarqube-db-data:/var/lib/postgresql/data

networks:
  sonarqube-network:
    driver: bridge

volumes:
  mysql-data:
  sonarqube-db-data:
